ktor {
  deployment {
    host = localhost
    port = 7000
  }
  application {
    modules = [
      io.github.damir.denis.tudor.ktor.registry.RegistryKt.module
    ]
  }
  registry {
    gossipFanout = 3
    gossipActionTimeout = 60

    peersInitialDelay = 5
    peersDiscoveryInterval = 600

    registryCleanUpInterval = 50
    registryDnsPattern = localhost
  }
}