ktor {
  deployment {
    host = localhost
    port = 9002
  }
  application {
    modules = [
      io.github.damir.denis.tudor.ktor.discoverable.DiscoverableKt.module
    ]
  }
  discoverable {
    heartbeatInterval = 5
    timeToLiveInterval = 10

    serviceRegistryHostname = "localhost"
    serviceRegistryPort = 7000

    servicePattern = "test"
    serviceIdentity = ${ktor.deployment.port}
  }
}
