ktor {
  deployment {
    host = localhost
    port = 9006
  }
  application {
    modules = [
      io.github.damir.denis.tudor.ktor.discoverable.DiscoverableKt.module
    ]
  }
  discoverable {
    heartbeatInterval = 30
    timeToLiveInterval = 600

    serviceRegistryHostname = "localhost"
    serviceRegistryPort = 7000
    serviceRegistryRetryInterval = 10

    servicePattern = "test"
    serviceIdentity = ${ktor.deployment.port}
  }
}
