ktor {
  deployment {
    host = localhost
    port = 9006
  }
  application {
    modules = [
      io.github.damir.denis.tudor.ktor.discoverable.DiscoverableKt.module
    ]
  }
  discoverable {
    heartbeatInterval = 10
    timeToLiveInterval = 20

    serviceRegistryHostname = "localhost"
    serviceRegistryPort = 7000
    serviceRegistryRetryInterval = 10

    servicePattern = "test"
    serviceIdentity = ${ktor.deployment.port}

    serviceMetadata = {
      routing-key = "test"
      test = "test"
    }
  }
}
