ktor{
  deployment{
    port = 8000
  }
  application{
    modules = [
      io.github.damir.denis.tudor.ktor.registry.DiscovererKt.module
    ]
  }
  discoverer {
    serviceRegistryHostname = localhost
    serviceRegistryPort = 7000
    servicesInvalidationInterval = 5
  }
}